libapp/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^(?P<item_id>\d+)/$', views.detail, name='detail'),
    url(r'^newitem/$',views.newitem, name='newitem'),
    url(r'^suggestions/$',views.suggestions, name='suggestions'),
    url(r'^searchlib/$', views.searchlib, name='searchlib'),
    url(r'^searchresult', views.searchresult, name='searchresult'),
    url(r'^user_login/$',views.user_login, name='user_login'),
    url(r'^user_logout/$',views.user_logout, name='user_logout'),
    url(r'^myitems/$', views.myitems, name='myitems'),
    url(r'^forgot_password/', views.forgot_password, name='forgot_password'),
    url(r'^register/$', views.register, name='register'),
    # url(r'^helloworld$', views.helloworld, name='hello world')
]

libsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^libapp/', include('libapp.urls', namespace='libapp')),
]

libapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


def clean_fields(value):
    if value < 1900 or value > 2016:
        raise ValidationError('pubyr must be between 1900 and 2016')


class Libuser(User):
    PROVINCE_CHOICES = (
        ('AB', 'Alberta'),  # The first value is actually stored in db, the second is descriptive
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    phone = models.IntegerField(null=True)
    postalcode = models.CharField(max_length=7, null=True, blank=True)


class Libitem(models.Model):
    TYPE_CHOICES = (
        ('Book', 'Book'),
        ('DVD', 'DVD'),
        ('Other', 'Other'),
    )
    title = models.CharField(max_length=100)
    itemtype = models.CharField(max_length=6, choices=TYPE_CHOICES, default='Book')
    checked_out = models.BooleanField(default=False)
    user = models.ForeignKey(Libuser, default=None, null=True, blank=True)
    duedate = models.DateField(default=None, null=True, blank=True)
    last_chkout = models.DateField(default=None, null=True, blank=True)
    date_acquired = models.DateField(default=datetime.date.today())
    pubyr = models.IntegerField(validators=[clean_fields])
    num_chkout = models.IntegerField(default=0)

    def __str__(self):
        return self.title



    def overdue(self):
        if self.checked_out == True:
            if self.duedate < datetime.date.today():
               return "Yes"
            else:
                return "No"


class Book(Libitem):
    CATEGORY_CHOICES = (
        (1, 'Fiction'),
        (2, 'Biography'),
        (3, 'Self Help'),
        (4, 'Education'),
        (5, 'Children'),
        (6, 'Teen'),
        (7, 'Other'),
    )
    author = models.CharField(max_length=100)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)

    def __str__(self):
        return self.title + ' by ' + self.author


class Dvd(Libitem):
    Rating_CHOICES = [
        (1, 'G'),
        (2, 'PG'),
        (3, 'PG-13'),
        (4, '14A'),
        (5, 'R'),
        (6, 'NR'),
    ]
    maker = models.CharField(max_length=100)
    duration = models.IntegerField(default=0)
    rating = models.IntegerField(choices=Rating_CHOICES)

    def __str__(self):
        return self.title + ' by ' + self.maker


class Suggestion(models.Model):
    TYPE_CHOICES = (
        (1, 'Book'),
        (2,'DVD'),
        (3, 'Other'),
    )
    title = models.CharField(max_length=100)
    pubyr = models.IntegerField(null=True, blank=True, validators=[clean_fields])
    type = models.IntegerField(default=1, choices=TYPE_CHOICES)
    cost = models.IntegerField()
    num_interested = models.IntegerField()
    comments = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.title

libapp/forms.py
from django import forms
from libapp.models import Suggestion,Libitem,Libuser


class SuggestionForm(forms.ModelForm):
    class Meta:
        model=Suggestion
        fields = ['title','pubyr','type','cost','comments']
        widgets = {'type':forms.RadioSelect(), }
        labels = {
            'pubyr':u'Publication Year','cost':u'Estimated cost in Dollars',
        }
# from django import forms
# from libapp.models import Suggestion
#
#

# class SuggestionForm(forms.ModelForm):
#     model = Suggestion
#     title = forms.CharField(max_length=100)
#     pubyr = forms.IntegerField()
#     type = forms.ChoiceField(widget=forms.RadioSelect())
#     cost = forms.IntegerField(label='Estimated Cost in Dollars')
#     num_interested = forms.IntegerField()
#     comments = forms.CharField(widget=forms.Textarea())

class SearchlibForm(forms.ModelForm):
    class Meta:
        model = Libitem
        fields = ['title']
    title = forms.CharField(max_length=100, required=False)
    by = forms.CharField(max_length=100, required=False)


class UserForm(forms.ModelForm):
    class Meta:
        model = Libuser
        fields = ['username', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput
        }

libapp/views.py
# from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from libapp.models import Book, Dvd, Libuser, Libitem, Suggestion,User
from django.shortcuts import get_object_or_404, render, render_to_response
from libapp.forms import SuggestionForm, SearchlibForm,UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from random import randint
from django.template import RequestContext
from datetime import datetime
from django.core.mail import send_mail



def index(request):
    itemlist = Libitem.objects.all().order_by('title')[:10]
    return render(request, 'libapp/index.html', {'itemlist': itemlist, 'user': request.user})




def about(request):
    c = RequestContext(request)
    visits = int(request.COOKIES.get('visits', '0'))
    if 'last_visit' in request.COOKIES:
        last_visit = request.COOKIES['last_visit']
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")
        if (datetime.now() - last_visit_time).seconds > 0:
            response = render_to_response('libapp/about.html', {'visits': visits + 1}, c, {'user': request.user})
            response.set_cookie('visits', visits + 1)
            response.set_cookie('last_visit', datetime.now())
    else:
        response = render_to_response('libapp/about.html', {'visits': visits + 1}, c, {'user': request.user})
        response.set_cookie('visits', visits + 1)
        response.set_cookie('last_visit', datetime.now())

    return response


def detail(request, item_id):
    # item = Libitem.objects.get(id=item_id)
    item = get_object_or_404(Libitem, pk=item_id)
    return render(request, 'libapp/detail.html', {'item': item})


def suggestions(request):
    suggestionlist = Suggestion.objects.all()[:10]
    return render(request, 'libapp/suggestions.html', {'itemlist': suggestionlist})



def newitem(request):
    suggestions = Suggestion.objects.all()
    if request.method == 'POST':
        form = SuggestionForm(request.POST)
        if form.is_valid():
            suggestion = form.save(commit=False)
            suggestion.num_interested = 1
            suggestion.save()
            return HttpResponseRedirect(reverse('libapp:suggestions'))
        else:
            return render(request, 'libapp/newitem.html', {'form': form, 'itemlist': suggestions})
    else:
        form = SuggestionForm()
        return render(request, 'libapp/newitem.html', {'form': form, 'itemlist': suggestions})


def searchlib(request):
    form = SearchlibForm()
    return render(request, 'libapp/searchlib.html', {'form': form})


def searchresult(request):
    form = SearchlibForm(request.GET)
    if request.GET.get("title") != '':
        booklist = Book.objects.filter(title__contains=request.GET.get("title"))
        dvdlist = Dvd.objects.filter(title__contains=request.GET.get("title"))
        if request.GET.get("by") != '':
            booklist = booklist.filter(author__contains=request.GET.get("by"))
            dvdlist = dvdlist.filter(maker__contains=request.GET.get("by"))
        return render(request, 'libapp/searchlib.html', {'form': form, 'booklist': booklist, 'dvdlist': dvdlist})
    elif request.GET.get("by") != '':
        booklist = Book.objects.filter(author__contains=request.GET.get("by"))
        dvdlist = Dvd.objects.filter(maker__contains=request.GET.get("by"))
        return render(request, 'libapp/searchlib.html', {'form': form, 'booklist': booklist, 'dvdlist': dvdlist})
    else:
        return render(request, 'libapp/searchlib.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        luckynum = randint(0, 9)
        if request.session.get('luckynum') == None :
            request.session['luckynum'] = luckynum
            request.session.set_expiry(3600)
        else:
            luckynum = 0
            request.session['luckynum'] = luckynum
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('libapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'libapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('libapp:index')))


def myitems(request):
    if request.user.is_authenticated():
        libitem = Libitem.objects.filter(checked_out=True).filter(user_id=request.user)
        return render(request, 'libapp/myitems.html', {'itemlist': libitem,'msg':''})
    else:
        msg = "You are not libuser"
        return render(request, 'libapp/myitems.html', {'msg': msg})


def forgot_password(request):
    if request.method == 'POST':
        username=request.POST['username']
        user=User.objects.get(username=username)
        if user:
            password = User.objects.make_random_password()
            user.set_password(password)
            user.save()
            msg='Your password is:'+password
            send_mail(
                'Password Recovery',
                msg,
                'ghumanharpuneet@gmail.com',
                [user.email],
                fail_silently=False,
            )
            return HttpResponseRedirect(reverse('libapp:user_login'))
        else:
            return render(request, 'libapp/forgot_password.html', {'msg':'Invalid username. Please contact administrator.'})
    else:
        return render(request, 'libapp/forgot_password.html', {'msg':''})



def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = Libuser.objects.create_user(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password'],
            email=form.cleaned_data['email']
            )
            return HttpResponseRedirect(reverse('libapp:index'))
    else:
        form = UserForm()
        return render(request, 'libapp/register.html', {'form': form})

libapp/templates/libapp/about.html
{% extends 'libapp/base.html' %}

{% block body_block %}
    <table class="table table-hover table-striped table-bordered">
        <tr><td colspan="2" align="center">Number of Visits {{ visits }}</td></tr>
        <tr><td colspan="2" align="center"><strong>This is about page</strong></td></tr>
    </table>
{% endblock %}

libapp/templates/libapp/about_old.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>My Library APP</title>
</head>

<body>
        <h2>This is about page</h2>
</body>
</html>
<p><a href="{% url 'libapp:index' %}">Index page</a></p>
<p><a href="/libapp">Index page</a></p>

libapp/templates/libapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

   <link rel="stylesheet" type="text/css" href="{% static 'libapp/bootstrap.min.css' %}" />
   <link rel="stylesheet" type="text/css" href="{% static 'libapp/bootstrap-theme.min.css' %}" />
   <link rel="stylesheet" type="text/css" href="{% static 'libapp/bootstrap-theme.css' %}" />
   <link rel="stylesheet" type="text/css" href="{% static 'libapp/bootstrap.css' %}" />


<html>
    <head>

        <title>MAC Library APP - {% block title %}Welcome!{% endblock %}</title>
    </head>

    <body>
        {% if user.is_authenticated %}
          <p align="center"><strong>Hello {{ user.username }}</strong></p>
        {% else %}
          <p ></p>
            <p></p>
        {% endif %}
         <div class="table-responsive">
            <table class="table table-hover table-striped table-bordered">
                <tr>
                    <td><a href="{% url 'libapp:about' %}">Find out about this site</a><br/><a href="{% url 'libapp:user_login' %}">Login</a></td>
                    <td><a href = "{% url 'libapp:index' %}">Click here to return to main page</a><br/><a href="{% url 'libapp:register' %}">Register</a></td>
                    {% if user.is_authenticated %}
                        <td><a href="{% url 'libapp:myitems' %}">My Items</a></br><a href="{% url 'libapp:user_logout' %}">Logout</a></td>
                    {% endif %}
                </tr>
                <tr>
                    <td><a href = "{% url 'libapp:suggestions' %}">Click here to find out Suggestions</a></td>
                    <td><a href="{% url 'libapp:searchlib' %}">Search</a></td>
                </tr>
            </table>

        </div>
         <hr />
        <div class="row">
            <h1 class="bg-primary">{% block myhdg %} {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
        </div>


    </body>
</html>

libapp/templates/libapp/detail.html
{% extends 'libapp/base.html' %}

{% block body_block %}
     <table class="table table-hover table-striped table-bordered">
      <tr><td width="30%"></td><td width="40%">
   {% if item %}
        <table class="table table-hover table-striped table-bordered">
        <tr><td colspan="2" align="center">ITEM DETAIL</td></tr>
                 <tr ><td> Title</td><td>  {{ item.title}} </td></tr>
                 <tr ><td> Publication year</td><td>  {{ item.pubyr}} </td></tr>
                {% if item.itemtype == 'Book' %}
                   <tr ><td> Author  </td><td> {{ item.book.author}} </td></tr>
                   <tr ><td> Category </td><td>  {{ item.book.category}} </td></tr>
                {% elif item.itemtype == 'DVD' %}
                     <tr ><td> Maker</td><td>  {{ item.dvd.maker}} </td></tr>
                     <tr ><td> Duration</td><td>  {{ item.dvd.duration}} </td></tr>
                     <tr ><td> Rating</td><td>  {{ item.dvd.rating}} </td></tr>
                {% endif %}
       </table>

    {% else %}
        <strong>There are no available items!</strong>
    {% endif %}

      </td><td width="30%"></td></tr> </table>
{% endblock %}

libapp/templates/libapp/detail_old.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>My Library APP</title>
</head>

<body>
    {% if item %}
        <h2>Library items</h2>
        <ol>
                <li> Title:  {{ item.title}} </li>
                <li> Pubyear:  {{ item.pubyr}} </li>
                {% if item.itemtype == 'Book' %}
                  <li> Author:  {{ item.book.author}} </li>
                  <li> category:  {{ item.book.category}} </li>
                {% elif item.itemtype == 'DVD' %}
                    <li> Maker:  {{ item.dvd.maker}} </li>
                    <li> Duration:  {{ item.dvd.duration}} </li>
                    <li> Rating:  {{ item.dvd.rating}} </li>
                {% endif %}
        </ol>

    {% else %}
        <strong>There are no available items!</strong>
    {% endif %}
</body>
</html>
{#<p><a href="/libapp/about">About page</a></p>#}
<p><a href="{% url 'libapp:about' %}">About page</a></p>
<p><a href="{% url 'libapp:index' %}">Index page</a></p>

libapp/templates/libapp/forgot_password.html
{% extends 'libapp/base.html' %}

{% block body_block %}
     <strong>{{ msg }}</strong>
    <table class="table table-hover table-striped table-bordered">

         <form action="{% url 'libapp:forgot_password' %}" method="post">

         {% csrf_token %}
           <div class="container">

                  <h4> Forgot Password</h4>
                  <form role="form">
                    <div class="form-group">
                      <label for="email">Username:</label>
                      <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
                    </div>

                     <button type="submit" class="btn btn-default">Submit</button>
                  </form>
           </div>
         </form>
    </table>
{% endblock %}

libapp/templates/libapp/index.html
{% extends 'libapp/base.html' %}

{% block body_block%}

      <table class="table table-hover table-striped table-bordered">

      <tr><td width="30%"></td><td width="40%">
      {% if request.session.luckynum %}
           <p align="'center">    Lucky number {{ request.session.luckynum }}</p>
       {% endif%}
           {% if itemlist %}
        <h3>List of Library items</h3>
         <table class="table table-hover table-striped table-bordered">
         <tr ><td> <strong>Item Type </strong></td><td><strong>Item Name</strong></td></tr>
            {% for item in itemlist %}
                <tr><td>{{ item.itemtype }}: </td> <td> <a href="{% url 'libapp:detail' item.id %}"> {{ item}}</a> </td> </tr>
            {% endfor %}
       </table>

    {% else %}
        <strong>There are no available items!</strong>
    {% endif %}
      </td><td width="30%"></td></tr>
      </table>

{% endblock %}

libapp/templates/libapp/index_old.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>My Library APP</title>
</head>

<body>
    {% if itemlist %}
        <h2>List of Library items</h2>
        <ol>
            {% for item in itemlist %}
                <li> {{ item.itemtype }}:  <a href="{% url 'libapp:detail' item.id %}">{{ item}}</a> </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available items!</strong>
    {% endif %}
</body>
</html>
{#<p><a href="/libapp/about">About page</a></p>#}
<p><a href="{% url 'libapp:about' %}">About page</a></p>

libapp/templates/libapp/login.html
{% extends 'libapp/base.html' %}
  {% block body_block%}
   {% if form.errors %}
       <p>Your username and password didn't match. Please try again.</p>
   {% endif %}

    <table class="table table-hover table-striped table-bordered">
      <tr><td width="30%"></td><td width="40%">

   <form action="{% url 'libapp:user_login' %}" method="post">
     {% csrf_token %}
      <table class="table table-hover table-striped table-bordered">
       <tr>
           <td>  <label>Username</label> </td>   <td> <input type="text" id="username" name="username"  placeholder="Username"></td>
       </tr>
        <tr>
             <td>  <label>Password</label></td><td>  <input type="password" name="password" id="password" placeholder="Password"> </td>
       </tr>
      </table>
      <input type="submit" value="login" class="btn btn-primary" />
       <a class="btn btn-primary" href= "{% url 'libapp:forgot_password'%}">Forgot Password</a>
   </form>

     </td><td width="30%"></td></tr>

      </table>
{% endblock %}

libapp/templates/libapp/myitems.html
{% extends 'libapp/base.html' %}
{% block title %}
    Items
{% endblock %}
{% block body_block %}
    <div>
        {% if user.is_authenticated %}
        {% if itemlist %}
        <table class="table table-hover table-striped table-bordered">
            <h2 align="center">List of items</h2>
            {% for item in itemlist %}
                <tr><td colspan="2" align="center">{{ item.title}}</td></tr>
                <tr><td align="center"> Item Type</td><td>{{ item.itemtype }}</td></tr>
                <tr><td align="center"> Publish Year</td><td> {{ item.pubyr }}</td></tr>
            {% endfor %}
        </table>

        {% else %}

            <table class="table table-hover table-striped table-bordered">
                <h2 colspan="2" align="center">List of items</h2>
                <tr><td colspan="2" align="center">There are no items checked out by you!</td></tr>
            </table>
        {% endif %}
        {% else %}
             <table class="table table-hover table-striped table-bordered">
                <tr><td><strong>{{ msg }}</strong></td></tr>
            </table>
        {% endif %}
    </div>
{% endblock %}

libapp/templates/libapp/newitem.html
{% extends 'libapp/base.html' %}
{% block title %}
    New Item
{% endblock %}
{% block body_block %}
     <table class="table table-hover table-striped table-bordered">
      <tr><td width="20%"></td><td width="60%">


    <div >
        <h2>SUGGESTED ITEMS</h2>
    </div>
    <table >
         <table class="table table-hover table-striped table-bordered">
            <tr >
                <td colspan="3" align="center"> <strong>Books</strong> </td>
            </tr>
            <div >
                {% if itemlist %}

                    {% for item in itemlist %}
                        {% if item.get_type_display == "Book" %}
                            <tr><td>{{ item.title}} </td> <td>{{ item.pubyr }} </td> <td>${{ item.cost }} </td> </tr>
                        {% endif %}
                    {% endfor %}

                {% else %}
                    <strong>There are no available items!</strong>
                {% endif %}
            </div>
        </table>
        <table >
            <table class="table table-hover table-striped table-bordered">
            <tr >
                <td colspan="3" align="center"> <strong>DVD</strong> </td>
            </tr>
            <div >
                {% if itemlist %}
                    {% for item in itemlist %}
                        {% if item.get_type_display == "DVD" %}
                            <tr><td>{{ item.title}} </td> <td>{{ item.pubyr }} </td> <td>${{ item.cost }} </td> </tr>
                        {% endif %}
                    {% endfor %}

                {% else %}
                    <strong>There are no available items!</strong>
                {% endif %}
            </div>
        </table>
    </div>

        <br/>
   <hr/>
        <br/>

         <table class="table table-hover table-striped table-bordered">
        <tr ><td colspan="2"> <h2>Fill this form to Submit New Item</h2> </td> </tr>
            <form name="myForm" action="{% url 'libapp:newitem' %}"  method="post">
                {% csrf_token %}

                <tr><td colspan="2" align="center">
                    <div class="controls">
                        <span class="help-inline" color="red">
                            {% for error in  form.pubyr.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </td></tr>

                <tr><td>Title</td> <td>{{ form.title }}</td> </tr>
                 <tr> <td>Publication Year</td> <td>{{ form.pubyr }} </td> </tr>
                 <tr><td>Amount In Dollar</td> <td>{{ form.cost }}</td> </tr>
                 <tr><td>Item Type</td> <td>{{ form.type }}</td> </tr>
                 <tr><td>Comments</td> <td>{{ form.comments }}</td> </tr>
                 <tr><td colspan="2" align="center"> <input type="submit" value="Submit" class="btn btn-success"></td>
            </form>
    </table>

      </td><td width="20%"></td></tr>
      </table>

{% endblock %}

libapp/templates/libapp/register.html
{% extends "libapp/base.html" %}

{% block body_block %}

  {% if form.errors %}
       <p>Please try again.</p>
  {% endif %}


        <table class="table table-hover table-striped table-bordered">
      <tr><td width="30%"></td><td width="40%">
      <h1>Create an account</h1>
   <form name="myForm" action="{% url 'libapp:register' %}"  method="post">
     {% csrf_token %}
      <table class="table table-hover table-striped table-bordered">
       <tr>
           <td>  <label>Username</label> </td>   <td> <input id="id_username" maxlength="30" name="username" type="text" required="required"/></td>
       </tr>
        <tr>
             <td>  <label>Email address:</label></td><td>  <input id="id_email" maxlength="254" name="email" type="email" required="required"/> </td>
       </tr>
          <tr>
             <td>  <label>Password:</label></td><td>  <input id="id_password" maxlength="128" name="password" type="password" required="required"/> </td>
          </tr>
      </table>
       <input type="submit" value="Create the account" class="btn btn-primary">
   </form>

     </td><td width="30%"></td></tr>

      </table>
{% endblock %}

libapp/templates/libapp/searchlib.html
{% extends 'libapp/base.html' %}
{% block title %}
    Suggestions
{% endblock %}
{% block body_block %}
     <table class="table table-hover table-striped table-bordered">
      <tr><td width="30%"></td><td width="40%">
    <div>
            <strong>Search</strong>
         <table class="table table-hover table-striped table-bordered">
             <tr><td>Title</td><td>By</td><td></td></tr>
             <tr><td colspan="3">
              <form action="{% url 'libapp:searchresult' %}" method="get">
                {% csrf_token %}
                {{ form.title }}
                {{ form.by }}
                <input type="submit" value="Search" class="btn btn-success">
            </form>
             </td></tr>

             </table>
    </div>
    <div>
            <h2>List of Searched items</h2>
    </div>
    <div>

        <div>
            <div>
                <strong>Books</strong>
            </div>
            <div>
                {% if booklist %}
                 <table class="table table-hover table-striped table-bordered">
                    {% for item in booklist %}
                        {% if item.itemtype == "Book" %}
                            <tr><td colspan="2" align="center"> <a href="{% url 'libapp:detail' item.id %}">{{ item.title}} </a> </td></tr>
                                <tr><td> Author </td> <td> {{ item.author }}</td> </tr>
                        {% endif %}
                    {% endfor %}
                </table>

                {% else %}

                {% endif %}
            </div>
        </div>
        <div>
            <div>
                <strong>DVDs</strong>
            </div>
            <div>
                {% if dvdlist %}
                <table class="table table-hover table-striped table-bordered">
                    {% for item in dvdlist %}
                        {% if item.itemtype == "DVD" %}
                        <tr><td colspan="2" align="center"> <a href="{% url 'libapp:detail' item.id %}">{{ item.title}} </a> </td></tr>
                                <tr><td> Maker</td><td> {{ item.maker }}</td></tr>
                        {% endif %}
                    {% endfor %}
                </table>

                {% else %}
                    <strong> </strong>
                {% endif %}
            </div>
        </div>
    </div>
     </td><td width="30%"></td></tr>
      </table>
{% endblock %}

libapp/templates/libapp/suggestions.html
{% extends 'libapp/base.html' %}
{% block title %}
    Suggestions
{% endblock %}
{% block body_block %}

    <table class="table table-hover table-striped ">
      <tr><td width="25%"></td><td width="50%">

    <div class="row" align="center">
            <h3 align="center">List of Suggested Items</h3>
            <a href="{% url 'libapp:newitem' %}" class="btn btn-success">New Item</a>
    </div>
      <br/>
    <div class="row">
        <div>
            <div>
                {% if itemlist %}
                <table class="table table-hover table-striped ">
                <tr><td colspan="3" align="center"> BOOK</td></tr>
                <tr><td>Title</td><td>Pub Year</td><td>Cost</td></tr>
                    {% for item in itemlist %}
                        {% if item.get_type_display == "Book" %}
                            <tr><td>{{ item.title}} </td><td>{{ item.pubyr }} </td><td>${{ item.cost }} </td></tr>
                        {% endif %}
                    {% endfor %}
                </table>

                {% else %}
                    <strong>There are no available items!</strong>
                {% endif %}
            </div>
        </div>

        <div>

            <div>
                {% if itemlist %}
                 <table class="table table-hover table-striped ">
                  <tr><td colspan="3" align="center"> DVD</td></tr>
                <tr><td>Title</td><td>Pub Year</td><td>Cost</td></tr>
                    {% for item in itemlist %}
                        {% if item.get_type_display == "DVD" %}
                            <tr><td>{{ item.title}} </td><td> {{ item.pubyr }} </td><td> ${{ item.cost }}</td></tr>
                        {% endif %}
                    {% endfor %}
                </table>

                {% else %}
                    <strong>There are no available items!</strong>
                {% endif %}
            </div>
        </div>
    </div>

    </td><td width="25%"></td></tr>
    </table>
{% endblock %}